name: Automated API tests using Postman CLI

on: 
  push:
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "16725446-24cc6844-85d2-4d55-90fa-a9e81fefb627" -e "16725446-3b6e3068-dd55-4189-8e64-71ed0ec89ba2"
          postman monitor run 1f094e2e-d954-4d70-9c24-3590b532e2ab
      - name: Lint Spec
        run: |
          postman spec lint 9d813d85-ced4-42de-8efa-0d7233605ba8
    
